namespace ParseCreditKarmaHarFile
{
    public class CsvEntry
    {
        public string Date { get; set; } = default!;
        public string  Description { get; set; } = default!;
        public string  OriginalDescription { get; set; } = default!;
        public string  Amount { get; set; } = default!;
        public string  TransactionType { get; set; } = default!;
        public string  Category { get; set; } = default!;
        public string  AccountName { get; set; } = default!;
        public string  Labels { get; set; } = default!;
        public string  Notes { get; set; } = default!;
    }

    public static class CsvEntryExtensions
    {
        /// <summary>
        /// Generate CSV string from list of CSV entries.
        /// 
        /// NOTE: Generated by Copilot
        /// </summary>
        /// <param name="transactions"></param>
        /// <returns></returns>
        public static string GenerateCsvString(this List<CsvEntry> transactions)
        {
            // Create the header row
            string headerRow = "Date,Description,OriginalDescription,Amount,TransactionType,Category,AccountName,Labels,Notes";

            // Create a comma-separated string from the list (including the header)
            return headerRow + "\n" +
                string.Join("\n", transactions.Select(entry =>
                    $"\"{entry.Date}\",\"{entry.Description}\",\"{entry.OriginalDescription}\",\"{entry.Amount}\",\"{entry.TransactionType}\"," +
                    $"\"{entry.Category}\",\"{entry.AccountName}\",\"{entry.Labels}\",\"{entry.Notes}\""));
        }

    }
}
